bot:
  commands_allow_edit: true
  commands_enabled: true
  commands_group_abbrev: true
  commands_level_getter: null
  commands_mention_rules: {everyone: false, here: false, role: true, user: true}
  commands_prefix: ''
  commands_require_mention: true
  levels: {userID: 'owner', roleID: 'mod'}
  plugin_config_dir: config
  plugin_config_format: json
  plugin_config_provider: null
  plugins: ['Plugin', 'AnotherPlugin']
  storage_config: {}
  storage_enabled: true
  storage_provider: memory
encoder: json
manhole_bind: !!python/tuple [127.0.0.1, 8484]
manhole_enable: false
max_reconnects: 5
shard_count: 1
shard_id: 0
token: 'Your-Discord-Token'
